name: Chemical_Metablomics

channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9.16
  - rdkit=2023.03.1
  - numpy=1.24.3
  - pandas=1.5.3
  - pyteomics
  - pip=23.1.2
  - pip:
    - matplotlib
    - tqdm==4.65.0
    - lxml
    - xmltodict